apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name:  database
stringData:
  AUTH_DB:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  AI_DB:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  PROJECT_DB:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

---

apiVersion: v1
kind: Secret
metadata:
  name: ai
type: Opaque
stringData:
  MISTRAL_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX



--- 

apiVersion: v1
kind: Secret
metadata:
  name: auth
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  REFRESH_TOKEN_SECRET:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

   

---

apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
